// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Constraints is an autogenerated mock type for the Constraints type
type Constraints struct {
	mock.Mock
}

// NewConstraints creates a new instance of Constraints. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConstraints(t interface {
	mock.TestingT
	Cleanup(func())
}) *Constraints {
	mock := &Constraints{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
